name: tests

on:
  pull_request:
    branches:
      - "16.0*"
  push:
    branches:
      - "16.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: docker.io/onestein/odoo-ci:16.0
    name: Odoo
    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Install external dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install odoo_test_helper
      - name: Initialize test db
        run: oca_init_test_database
        env:
          ADDONS_DIR: .
          ODOO_VERSION: "16.0"
      - name: Run tests
        run: oca_run_tests
        env:
          ADDONS_DIR: .
          ODOO_VERSION: "16.0"
      - name: Prepare report
        run: coverage xml -o coverage.xml --data-file .coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
